### ISSUE TITLE
IndexOutOfBoundsException in HashMap#removed

### ISSUE THREAD

**Issue by durban** [typelevel/cats-collections#590]
```scala
    val myHash: Hash[Int] = new Hash[Int] {
      final override def eqv(x: Int, y: Int): Boolean =
        (x % 8) === (y % 8)
      final override def hash(x: Int): Int =
        (x % 4)
    }
    val m = cats.collections.HashMap(1 -> 1, 8 -> 8, 4 -> 4)(myHash)
    m.removed(16)
```

```
java.lang.IndexOutOfBoundsException: -1 is out of bounds (min 0, max 1)
    at scala.collection.immutable.Vector.ioob(Vector.scala:276)
    at scala.collection.immutable.Vector1.apply(Vector.scala:382)
    at cats.data.NonEmptyVector$.getUnsafe$extension(NonEmptyVector.scala:53)
    at cats.collections.HashMap$CollisionNode.removed(HashMap.scala:626)
    at cats.collections.HashMap$BitMapNode.removeKeyValueFromSubNode(HashMap.scala:1025)
    at cats.collections.HashMap$BitMapNode.removed(HashMap.scala:1049)
    at cats.collections.HashMap$BitMapNode.removeKeyValueFromSubNode(HashMap.scala:1025)
    at cats.collections.HashMap$BitMapNode.removed(HashMap.scala:1049)
    at cats.collections.HashMap$BitMapNode.removeKeyValueFromSubNode(HashMap.scala:1025)
    at cats.collections.HashMap$BitMapNode.removed(HashMap.scala:1049)
    at cats.collections.HashMap$BitMapNode.removeKeyValueFromSubNode(HashMap.scala:1025)
    at cats.collections.HashMap$BitMapNode.removed(HashMap.scala:1049)
    at cats.collections.HashMap$BitMapNode.removeKeyValueFromSubNode(HashMap.scala:1025)
    at cats.collections.HashMap$BitMapNode.removed(HashMap.scala:1049)
    at cats.collections.HashMap$BitMapNode.removeKeyValueFromSubNode(HashMap.scala:1025)
    at cats.collections.HashMap$BitMapNode.removed(HashMap.scala:1049)
    at cats.collections.HashMap$BitMapNode.removeKeyValueFromSubNode(HashMap.scala:1025)
    at cats.collections.HashMap$BitMapNode.removed(HashMap.scala:1049)
    at cats.collections.HashMap.removed(HashMap.scala:206)
    ...
```

/cc @DavidGregory084

**Comment by gemelen** [comment]
@durban thank you for rising this issue.

**Comment by durban** [comment]
#592 _seems_ to fix the exception.
